DROP TABLE IF EXISTS pelicula;
CREATE TABLE IF NOT EXISTS pelicula(
   titulo        VARCHAR(49) NOT NULL PRIMARY KEY
  ,descripcion   VARCHAR(172) NOT NULL
  ,anio_estreno  INTEGER  NOT NULL
  ,idioma        VARCHAR(23) NOT NULL
  ,trama         VARCHAR(303) NOT NULL
  ,pais          VARCHAR(29) NOT NULL
  ,generos       VARCHAR(35) NOT NULL
  ,clasificacion VARCHAR(5) NOT NULL
  ,poster        VARCHAR(36) NOT NULL
);
INSERT INTO pelicula(titulo,descripcion,anio_estreno,idioma,trama,pais,generos,clasificacion,poster) VALUES
 ('Avengers: Endgame','Después de los devastadores eventos de Avengers: Infinity War, los superhéroes restantes se reúnen para deshacer las acciones de Thanos y restaurar el orden en el universo.',019,'Inglés','Después de la desaparición de la mitad de toda la vida en el universo, los Vengadores restantes deben reunirse y enfrentar su mayor desafío hasta ahora: encontrar una forma de revertir las acciones de Thanos y restaurar el equilibrio en el universo.','Estados Unidos','Acción, Aventura, Fantasía','PG-13','https://www.example.com/poster1.jpg')
,('Parasite','La vida de una familia pobre cambia cuando su hijo comienza a trabajar para una familia adinerada, desencadenando una serie de eventos impredecibles.',019,'Coreano','Un joven llamado Ki-woo se introduce en la casa de los Park haciéndose pasar por un tutor de inglés para las hijas de la familia. A medida que la relación de los Kim con los Park se vuelve más profunda, se ven envueltos en un incidente inesperado.','Corea del Sur','Drama, Comedia, Suspenso','R','https://www.example.com/poster2.jpg')
,('La La Land','Un pianista de jazz y una aspirante a actriz se enamoran en Los Ángeles mientras persiguen sus sueños de fama y fortuna.',016,'Inglés','En la ciudad de Los Ángeles, Mia, una aspirante a actriz, y Sebastian, un pianista de jazz, se enamoran mientras luchan por perseguir sus sueños en una ciudad conocida por destruir esperanzas y romper corazones.','Estados Unidos','Comedia musical, Drama, Romance','PG-13','https://www.example.com/poster3.jpg')
,('The Shawshank Redemption','Dos hombres encuentran redención en una prisión mientras forjan una profunda amistad a lo largo de los años.',1994,'Inglés','Andy Dufresne, un banquero injustamente condenado a cadena perpetua, encuentra esperanza y redención en la cárcel de Shawshank mientras se hace amigo de un prisionero llamado Red.','Estados Unidos','Drama','R','https://www.example.com/poster4.jpg')
,('Inception','Un ladrón de sueños realiza un último trabajo: implantar una idea en la mente de un individuo mientras sueña.',010,'Inglés','Dominic Cobb es un ladrón de sueños hábil que se especializa en la extracción de información valiosa del subconsciente de las personas mientras sueñan. Se le ofrece la oportunidad de realizar una tarea aparentemente imposible: implantar una idea en la mente de alguien.','Estados Unidos','Acción, Aventura, Ciencia ficción','PG-13','https://www.example.com/poster5.jpg')
,('The Godfather','La historia épica de la familia Corleone y su involucramiento en el crimen organizado.',197,'Inglés','El patriarca de la familia Corleone, Vito, transfiere el control de su imperio criminal a su hijo menor, Michael, lo que desencadena una serie de eventos violentos y una lucha por el poder dentro de la mafia.','Estados Unidos','Drama, Crimen','R','https://www.example.com/poster6.jpg')
,('Pulp Fiction','Una historia entrelazada sobre criminales, cajas misteriosas y una pareja danzarina.',1994,'Inglés','Pulp Fiction sigue a varias historias entrelazadas de criminales de Los Ángeles, incluyendo a dos asesinos a sueldo, un boxeador, un gánster y su esposa, y un par de ladrones de poca monta.','Estados Unidos','Crimen, Drama','R','https://www.example.com/poster7.jpg')
,('The Dark Knight','Batman se enfrenta a su némesis, el Joker, en una batalla por la ciudad de Gotham.',008,'Inglés','Batman se enfrenta al Joker, un villano psicópata que amenaza con sumir a Gotham City en el caos. Mientras Batman lucha contra el Joker, también debe lidiar con la corrupción dentro de la policía de la ciudad.','Estados Unidos','Acción, Crimen, Drama','PG-13','https://www.example.com/poster8.jpg')
,('The Matrix','Un hacker descubre que el mundo en el que vive es una simulación controlada por máquinas y se une a la resistencia humana para luchar contra ellas.',1999,'Inglés','Thomas Anderson, un programador de computadoras y hacker conocido como Neo, descubre que el mundo en el que vive es una simulación creada por máquinas inteligentes. Se une a un grupo de rebeldes humanos para luchar contra las máquinas y liberar a la humanidad.','Estados Unidos','Acción, Ciencia ficción','R','https://www.example.com/poster9.jpg')
,('Forrest Gump','La vida de Forrest Gump, un hombre de inteligencia limitada pero corazón bondadoso, quien se encuentra en medio de importantes eventos históricos.',1994,'Inglés','Forrest Gump es un hombre con discapacidad intelectual pero una determinación inquebrantable. A lo largo de su vida, se encuentra con importantes figuras históricas y se ve envuelto en eventos clave de la historia de Estados Unidos, mientras busca el amor y la felicidad.','Estados Unidos','Drama, Comedia','PG-13','https://www.example.com/poster10.jpg')
,('The Lord of the Rings: The Fellowship of the Ring','Un grupo de seres de diferentes razas se embarca en una épica aventura para destruir un poderoso anillo y salvar a la Tierra Media del malvado Señor Oscuro.',001,'Inglés','Frodo Baggins, un hobbit tímido, es elegido para llevar un anillo mágico al Monte del Destino y destruirlo para evitar que el Señor Oscuro Sauron lo recupere y sumerja a la Tierra Media en la oscuridad.','Estados Unidos, Nueva Zelanda','Aventura, Fantasía','PG-13','https://www.example.com/poster11.jpg')
,('The Great Gatsby','La historia de amor entre un hombre misterioso y una mujer casada durante la próspera era del jazz en la década de 1920.',013,'Inglés','Jay Gatsby, un hombre enigmático y millonario, se enamora de Daisy Buchanan, una mujer casada. Su obsesión por recuperar su amor perdido los lleva a un viaje de decadencia, pasión y tragedia durante la vibrante era del jazz en Nueva York.','Estados Unidos, Australia','Drama, Romance','PG-13','https://www.example.com/poster12.jpg')
,('Interstellar','Un grupo de astronautas viaja a través de un agujero de gusano en busca de un nuevo hogar para la humanidad debido a la crisis climática en la Tierra.',014,'Inglés','En un futuro donde la Tierra se enfrenta a una crisis climática devastadora, un grupo de astronautas emprende un viaje interestelar a través de un agujero de gusano en busca de un nuevo hogar para la humanidad.','Estados Unidos, Reino Unido','Aventura, Drama, Ciencia ficción','PG-13','https://www.example.com/poster13.jpg')
,('The Lion King','La historia de Simba, un joven león destinado a convertirse en rey y enfrentar a su malvado tío para reclamar su lugar en el ciclo de la vida.',1994,'Inglés','Simba, un joven león heredero del trono, es exiliado por su malvado tío Scar después de la muerte de su padre. Con la ayuda de nuevos amigos, Simba debe encontrar el coraje para enfrentarse a su pasado y reclamar su lugar como rey.','Estados Unidos','Animación, Aventura, Drama','G','https://www.example.com/poster14.jpg')
,('Titanic','La historia de amor trágica entre Rose y Jack, que se conocen a bordo del legendario transatlántico Titanic.',1997,'Inglés','Rose, una joven de clase alta, se enamora de Jack, un pasajero de tercera clase, a bordo del lujoso transatlántico Titanic. Su apasionado romance se ve amenazado por el trágico destino del barco.','Estados Unidos','Drama, Romance','PG-13','https://www.example.com/poster15.jpg')
,('The Avengers','Los superhéroes de Marvel se unen para enfrentarse a una amenaza extraterrestre que busca conquistar la Tierra.',01,'Inglés','Cuando un poderoso villano llamado Loki amenaza con invadir la Tierra, Nick Fury, el director de S.H.I.E.L.D., reúne a un grupo de superhéroes para detenerlo. Los Vengadores deben aprender a trabajar juntos y desplegar sus habilidades extraordinarias para proteger al planeta.','Estados Unidos','Acción, Aventura, Fantasía','PG-13','https://www.example.com/poster16.jpg')
,('Jurassic Park','Un multimillonario crea un parque temático con dinosaurios reales, pero las cosas salen mal cuando los dinosaurios escapan y comienzan a causar estragos.',1993,'Inglés','Un grupo de personas es invitado a visitar Jurassic Park, un parque temático lleno de dinosaurios clonados. Sin embargo, cuando el sistema de seguridad falla, los dinosaurios escapan y los visitantes deben luchar por sobrevivir mientras son perseguidos por las criaturas prehistóricas.','Estados Unidos','Aventura, Ciencia ficción, Suspenso','PG-13','https://www.example.com/poster17.jpg')
,('The Social Network','La historia del ascenso de Mark Zuckerberg y la creación de Facebook, la red social más popular del mundo.',010,'Inglés','Esta película narra la historia de Mark Zuckerberg, un estudiante de Harvard que crea el sitio web de redes sociales llamado Facebook. A medida que Facebook se vuelve cada vez más exitoso, Mark se enfrenta a demandas legales y traiciones personales mientras lucha por mantener el control de su creación.','Estados Unidos','Biografía, Drama','PG-13','https://www.example.com/poster18.jpg')
,('The Dark Knight Rises','Batman regresa para enfrentarse a Bane, un terrorista que amenaza a Gotham City.',01,'Inglés','Ocho años después de los eventos de The Dark Knight, Batman regresa para proteger a Gotham City de Bane, un enemigo formidable que busca sumir a la ciudad en el caos.','Estados Unidos, Reino Unido','Acción, Aventura, Crimen','PG-13','https://www.example.com/poster21.jpg')
,('The Pursuit of Happyness','La inspiradora historia de un padre soltero que lucha por construir una vida mejor para él y su hijo.',006,'Inglés','Basada en una historia real, la película sigue a Chris Gardner, un padre soltero que enfrenta dificultades financieras. A pesar de los desafíos, lucha por superar la adversidad y construir una vida mejor para él y su hijo.','Estados Unidos','Biografía, Drama','PG-13','https://www.example.com/poster22.jpg')
,('The Notebook','Una historia de amor épica y conmovedora que trasciende el tiempo y los obstáculos.',004,'Inglés','En la década de 1940, Allie, una joven adinerada, se enamora de Noah, un trabajador local. A pesar de las diferencias sociales y los obstáculos que enfrentan, su amor persiste a lo largo de los años, dejando una huella imborrable en sus vidas.','Estados Unidos','Drama, Romance','PG-13','https://www.example.com/poster23.jpg')
,('The Wolf of Wall Street','La historia de Jordan Belfort, un corredor de bolsa que se involucra en actividades fraudulentas y excesos desenfrenados.',013,'Inglés','Basada en hechos reales, la película sigue la vida de Jordan Belfort, un ambicioso corredor de bolsa que se involucra en actividades fraudulentas y lleva una vida de excesos desenfrenados, enfrentando las consecuencias de sus acciones.','Estados Unidos','Biografía, Comedia, Crimen','R','https://www.example.com/poster24.jpg')
,('Inglourious Basterds','Un grupo de soldados judíos y una espía se unen para llevar a cabo una misión letal durante la Segunda Guerra Mundial.',009,'Inglés, Alemán, Francés','Durante la Segunda Guerra Mundial, un grupo de soldados judíos conocidos como los Bastardos se unen con una espía alemana para llevar a cabo una misión de venganza contra líderes nazis, mientras conspiran para asesinar a Adolf Hitler.','Estados Unidos, Alemania','Aventura, Drama, Bélico','R','https://www.example.com/poster25.jpg')
,('Fight Club','Un hombre desilusionado forma un club de lucha clandestino como forma de escape de su vida monótona.',1999,'Inglés','Un hombre anónimo y desilusionado encuentra un escape de su vida monótona al formar un club de lucha clandestino, pero las cosas se complican cuando se involucra en un juego peligroso con consecuencias inesperadas.','Estados Unidos, Alemania','Drama','R','https://www.example.com/poster26.jpg')
,('The Grand Budapest Hotel','Las extravagantes aventuras de un conserje y su joven protegido en un famoso hotel europeo.',014,'Inglés','La película sigue las extravagantes aventuras de Gustave H., el conserje de un famoso hotel europeo, y Zero Moustafa, su joven protegido, mientras se ven envueltos en un robo, un asesinato y una búsqueda de un valioso tesoro.','Estados Unidos, Alemania','Comedia, Drama','R','https://www.example.com/poster27.jpg')
,('Eternal Sunshine of the Spotless Mind','Una pareja se somete a un procedimiento médico para borrar los recuerdos de su relación, pero el amor no se olvida tan fácilmente.',004,'Inglés','Joel y Clementine, una pareja que ha terminado su relación, se someten a un procedimiento médico experimental para borrar los recuerdos de su amor. Mientras sus recuerdos comienzan a desvanecerse, se dan cuenta de que todavía hay algo especial entre ellos.','Estados Unidos','Drama, Romance, Ciencia ficción','R','https://www.example.com/poster29.jpg')
,('The Matrix','Un programador descubre que el mundo en el que vive es una simulación y se une a una rebelión para luchar contra las máquinas que lo controlan.',1999,'Inglés','Thomas Anderson, un programador de computadoras conocido como Neo, descubre que la realidad en la que vive es una simulación creada por máquinas inteligentes. Se une a una rebelión humana para luchar contra las máquinas y liberar a la humanidad de su control.','Estados Unidos','Acción, Ciencia ficción','R','https://www.example.com/poster30.jpg')
,('The Silence of the Lambs','Una joven agente del FBI busca la ayuda de un psiquiatra caníbal para atrapar a un peligroso asesino en serie.',1991,'Inglés','Clarice Starling, una joven agente del FBI, busca la ayuda del brillante psiquiatra caníbal Dr. Hannibal Lecter para capturar a Buffalo Bill, un peligroso asesino en serie. Enfrentada a un juego psicológico aterrador, Clarice debe confiar en Lecter para resolver el caso.','Estados Unidos','Drama, Crimen, Suspenso','R','https://www.example.com/poster38.jpg')
,('The Green Mile','La historia de un guardia de prisión y su inusual relación con un prisionero con poderes misteriosos.',1999,'Inglés','The Green Mile sigue la vida de Paul Edgecomb, un guardia de prisión en el corredor de la muerte de una penitenciaría en 1930. La llegada de un prisionero llamado John Coffey, que posee poderes misteriosos, desafía las creencias y cambia la vida de Edgecomb para siempre.','Estados Unidos','Drama, Fantasía, Crimen','R','https://www.example.com/poster40.jpg')
,('The Exorcist','La posesión demoníaca de una niña y los intentos de un sacerdote por salvarla.',1973,'Inglés','The Exorcist sigue la historia de Regan MacNeil, una niña que es poseída por una entidad demoníaca. Su madre busca la ayuda de un sacerdote que se enfrenta a la lucha sobrenatural para salvar el alma de la niña.','Estados Unidos','Terror','R','https://www.example.com/poster41.jpg')
,('Psycho','La historia de Norman Bates, el propietario de un motel con oscuros secretos.',1960,'Inglés','Psycho sigue la vida de Norman Bates, un joven con una relación complicada con su madre y propietario de un motel aislado. Cuando una mujer se registra en el motel y desaparece misteriosamente, se desencadenan una serie de eventos perturbadores.','Estados Unidos','Terror, Suspenso','R','https://www.example.com/poster42.jpg')
,('The Shining','Un escritor y su familia se mudan a un hotel aislado donde se desatan fuerzas sobrenaturales.',1980,'Inglés','The Shining sigue a Jack Torrance, un escritor en busca de inspiración, y su familia mientras se mudan a un hotel aislado durante el invierno. Conforme la soledad y el aislamiento se apoderan de ellos, fuerzas sobrenaturales desencadenan la creciente locura de Jack.','Reino Unido, Estados Unidos','Terror, Drama','R','https://www.example.com/poster43.jpg')
,('Halloween','La historia de Michael Myers, un asesino enmascarado que aterroriza a una pequeña ciudad.',1978,'Inglés','Halloween sigue a Michael Myers, un asesino enmascarado que escapa del hospital psiquiátrico y aterroriza a la ciudad de Haddonfield en la noche de Halloween. La joven Laurie Strode se convierte en su principal objetivo mientras lucha por sobrevivir.','Estados Unidos','Terror','R','https://www.example.com/poster44.jpg')
,('A Nightmare on Elm Street','Un asesino sobrenatural acecha y asesina a adolescentes en sus sueños.',1984,'Inglés','A Nightmare on Elm Street sigue a un grupo de adolescentes acosados por Freddy Krueger, un asesino sobrenatural que acecha y asesina a sus víctimas en sus sueños. A medida que descubren la verdad detrás de su existencia, deben encontrar la forma de detenerlo antes de que sea demasiado tarde.','Estados Unidos','Terror','R','https://www.example.com/poster45.jpg')
,('American Beauty','La vida de una familia aparentemente perfecta se desmorona en medio de la insatisfacción y la búsqueda de la verdadera felicidad.',1999,'Inglés','American Beauty examina la vida de la familia Burnham y sus vecinos, revelando las tensiones y la insatisfacción ocultas debajo de una apariencia aparentemente perfecta. La película explora temas de belleza, deseo y búsqueda de la verdadera felicidad en una sociedad superficial.','Estados Unidos','Drama','R','https://www.example.com/poster49.jpg')
,('The Pursuit of Happyness','La inspiradora historia de un padre soltero que lucha por construir una vida mejor para él y su hijo.',006,'Inglés','Basada en una historia real, la película sigue a Chris Gardner, un padre soltero que enfrenta dificultades financieras. A pesar de los desafíos, lucha por superar la adversidad y construir una vida mejor para él y su hijo.','Estados Unidos','Biografía, Drama','PG-13','https://www.example.com/poster50.jpg');
